In [2]:
import numpy as np
a=np.array([[1,2,4],[5,6,7]])
print("Array created using passed list:\n",a)

Array created using passed list:
 [[1 2 4]
 [5 6 7]]


In [3]:
b=np.zeros((3,4))
print("\nAn array initalized with all zeros:\n",b)


An array initalized with all zeros:
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [6]:
c=np.full((3,3),6)
print("\nAn array initalized with all 6s:\n",c)


An array initalized with all 6s:
 [[6 6 6]
 [6 6 6]
 [6 6 6]]


In [8]:
d=np.random.random((2,2))
print("\nA random array:\n",d)


A random array:
 [[0.99035973 0.87788818]
 [0.67571405 0.79836805]]


In [10]:
e=np.arange(0,30,5)
print("\nA sequential array with steps of 5:\n",e)


A sequential array with steps of 5:
 [ 0  5 10 15 20 25]


In [12]:
arr=np.array([[1,2,3,4],[5,2,4,2],[1,2,0,1]])
newarr=arr.reshape(4,3)
print("\nOriginal array:\n",arr)
print("Reshaped array[4,3]:\n",newarr)


Original array:
 [[1 2 3 4]
 [5 2 4 2]
 [1 2 0 1]]
Reshaped array[4,3]:
 [[1 2 3]
 [4 5 2]
 [4 2 1]
 [2 0 1]]


In [13]:
flarr=arr.flatten()
print("\nOriginal array;\n",arr)
print("Flattened array:\n",flarr)


Original array;
 [[1 2 3 4]
 [5 2 4 2]
 [1 2 0 1]]
Flattened array:
 [1 2 3 4 5 2 4 2 1 2 0 1]


In [14]:
print("\nNo of dimensions: ",arr.ndim)


No of dimensions:  2


In [15]:
print("\nShape of array: ",arr.shape)


Shape of array:  (3, 4)


In [16]:
print("\nSize of array: ",arr.size)


Size of array:  12


In [17]:
print("\nArray stores elements of type: ",arr.dtype)


Array stores elements of type:  int64


In [18]:
newtype=arr.astype('f')
print("\nConverted array elements:\n",newtype)
print("Converted array type:",newtype.dtype)


Converted array elements:
 [[1. 2. 3. 4.]
 [5. 2. 4. 2.]
 [1. 2. 0. 1.]]
Converted array type: float32


In [21]:
p=np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12],[13,14,15]])
print(p[3:0:-1])

[[10 11 12]
 [ 7  8  9]
 [ 4  5  6]]


In [22]:
p=np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12],[13,14,15]])
print(p[2,0:2])

[7 8]


In [23]:
p=np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12],[13,14,15]])
print(p[2:,2:])

[[ 9]
 [12]
 [15]]


In [28]:
p=np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12],[13,14,15]])
print(p[3:,3:])

[]


In [29]:
p=np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12],[13,14,15]])
print(p[:,1])

[ 2  5  8 11 14]


In [30]:
p=np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12],[13,14,15]])
c=p.astype('f')
print(c)

[[ 1.  2.  3.]
 [ 4.  5.  6.]
 [ 7.  8.  9.]
 [10. 11. 12.]
 [13. 14. 15.]]


In [32]:
p=np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12],[13,14,15]])
c=p.astype('i')
print(c)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]]
